export default {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ERROR_FETCH_PRODUCTS: "ERROR_FETCH_PRODUCTS",
  FETCH_USER: "FETCH_USER",
  ERROR_FETCH_USER: "ERROR_FETCH_USER",
  FETCH_USER_CART: "FETCH_USER_CART",
  ERROR_FETCH_USER_CART: "ERROR_FETCH_USER_CART",
  FETCH_USER_ORDERS: "FETCH_USER_ORDERS",
  ERROR_FETCH_USER_ORDERS: "ERROR_FETCH_USER_ORDERS",
  ADD_TO_CART: "ADD_TO_CART",
  ERROR_ADD_TO_CART: "ERROR_ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ERROR_REMOVE_FROM_CART: "ERROR_REMOVE_FROM_CART",
  LOGIN_USER: "LOGIN_USER",
  ERROR_LOGIN_USER: "ERROR_LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  ERROR_SIGNUP_USER: "ERROR_SIGNUP_USER"
};
